version: '3.8'

services:
  store_api:
    container_name: store_api
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8081"
    command: go run store-service/cmd/store_api.go -b 0.0.0.0

  order_api:
    container_name: order_api
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    env_file:
      - .env
    ports:
      - "8082:8082"

  client_api:
    container_name: client_api
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    env_file:
      - .env
    ports:
      - "8083:8083"
    command: go run client-service/cmd/client_api.go -b 0.0.0.0

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
